"""Add Canvas table

Revision ID: 065397fbdf3a
Revises: 1fa36e52a515
Create Date: 2025-02-16 01:32:06.087980

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '065397fbdf3a'
down_revision = '1fa36e52a515'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
