"""Add Canvas table

Revision ID: 1fa36e52a515
Revises: 2c0ecfd4e072
Create Date: 2025-02-16 01:26:17.378598

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1fa36e52a515'
down_revision = '2c0ecfd4e072'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
