"""Optional field when creating canvas

Revision ID: 494e57b1dd83
Revises: 0b79021688e3
Create Date: 2025-02-20 20:20:38.145169

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '494e57b1dd83'
down_revision = '0b79021688e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
