"""Set default value for non required field in canvas model

Revision ID: 5728ce92d2e1
Revises: 6c3cf1396e47
Create Date: 2025-02-20 20:01:45.266924

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5728ce92d2e1'
down_revision = '6c3cf1396e47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('canvas', 'ideas',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('canvas', 'constraints',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('canvas', 'test_cases',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('canvas', 'code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('canvas', 'code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('canvas', 'test_cases',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('canvas', 'constraints',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('canvas', 'ideas',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
