"""Add Canvas table

Revision ID: 6c3cf1396e47
Revises: 065397fbdf3a
Create Date: 2025-02-16 01:53:16.209259

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6c3cf1396e47'
down_revision = '065397fbdf3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canvas',
    sa.Column('problem_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('problem_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('ideas', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('constraints', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('test_cases', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('canvas')
    # ### end Alembic commands ###
